# Generated by Django 6.0.7 on 2026-07-22 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="doctor",
            field=models.ForeignKey(
                limit_choices_to={"role": "doctor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctor_recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"role": "patient"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patient_recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
