# Generated by Django 6.0.7 on 2026-08-03 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_recipe_doctor_alter_recipe_patient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="clinic",
            field=models.ForeignKey(
                limit_choices_to={"role": "superadmin"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinic_recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
