# Generated by Django 6.0.7 on 2026-07-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[("in_progress", "In Progress"), ("completed", "Completed")],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
