# Generated by Django 6.0.7 on 2026-08-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0003_appointment_clinic"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_reminded",
            field=models.BooleanField(default=False),
        ),
    ]
