# Generated by Django 6.0.7 on 2026-07-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0002_treatmenttype_treatment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="tooth_number",
            field=models.PositiveIntegerField(),
        ),
    ]
