# Generated by Django 6.0.7 on 2026-07-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0004_service_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
