# Generated by Django 6.0.7 on 2026-07-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_remove_user_region"),
        ("clinic", "0005_service_is_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Region",
        ),
    ]
