# Generated by Django 6.0.7 on 2026-07-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0006_delete_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmenttype",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
