# Generated by Django 6.0.7 on 2026-07-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0007_treatmenttype_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="status",
            field=models.CharField(
                choices=[("in_progress", "In Progress"), ("completed", "Completed")],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
