# Generated by Django 6.0.7 on 2026-08-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0008_treatment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="treatment_type",
        ),
        migrations.DeleteModel(
            name="Material",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
