# Generated by Django 6.0.7 on 2026-08-03 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0009_remove_service_treatment_type_delete_material_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="clinic",
            field=models.ForeignKey(
                limit_choices_to={"role": "superadmin"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinic_treatments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
