# Generated by Django 6.0.7 on 2026-08-06 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0010_treatment_clinic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmenttype",
            name="clinic",
            field=models.ForeignKey(
                limit_choices_to={"role": "superadmin"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinic_treatment_types",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
