# Generated by Django 6.0.7 on 2026-08-26 08:29

import apps.authentication.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0011_treatmenttype_clinic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=14,
                        validators=[apps.authentication.utils.validate_number],
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="clinic/logo"),
                ),
                ("working_hours", models.JSONField(blank=True, null=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "superadmin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinic_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
