# Generated by Django 6.0.7 on 2026-08-27 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_remove_user_specialty_doctortype_user_doctor_type"),
        ("clinic", "0012_clinic"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmenttype",
            name="doctor_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctor_treatment_types",
                to="authentication.doctortype",
            ),
        ),
    ]
