# Generated by Django 6.0.7 on 2026-07-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="region",
        ),
    ]
