# Generated by Django 6.0.7 on 2026-07-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_remove_user_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="office",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
