# Generated by Django 6.0.7 on 2026-08-03 17:22

import apps.authentication.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0005_user_address_user_office"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="user",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "superadmin"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinic_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=14, validators=[apps.authentication.utils.validate_number]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                    ("admin", "Admin"),
                ],
                default="patient",
                max_length=200,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("phone_number", "clinic"), name="unique_phone_per_clinic"
            ),
        ),
    ]
