# Generated by Django 6.0.7 on 2026-08-06 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_user_options_user_clinic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="clinic",
            field=models.ForeignKey(
                limit_choices_to={"role": "superadmin"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinic_galleries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
