# Generated by Django 6.0.7 on 2026-08-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_gallery_clinic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_auth_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
