# Generated by Django 6.0.7 on 2026-08-27 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_user_telegram_auth_code_user_telegram_chat_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="specialty",
        ),
        migrations.CreateModel(
            name="DoctorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(default="Stomatolog", max_length=255)),
                (
                    "clinic",
                    models.ForeignKey(
                        limit_choices_to={"role": "superadmin"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_doctor_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="doctor_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctors",
                to="authentication.doctortype",
            ),
        ),
    ]
