# Generated by Django 6.0.7 on 2026-08-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_remove_user_specialty_doctortype_user_doctor_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctortype",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
